productpage:
  namespace: bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
  image: ghcr.io/nattaphonmek/bookinfo-productpage
  tag: prd
ingress:
  host: opsta.parfet.in.th
  path: "/productpage(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_HOSTNAME: http://opsta.parfet.in.th/ratings
  DETAILS_HOSTNAME: http://opsta.parfet.in.th/details
  REVIEWS_HOSTNAME: http://opsta.parfet.in.th/reviews
  FLOOD_FACTOR: 0