productpage:
  namespace: bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
  image: ghcr.io/nattaphonmek/bookinfo-productpage
  tag: prd
ingress:
  host: opsta.konmek.cloud
  path: "/productpage(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_HOSTNAME: https://opsta.konmek.cloud/ratings
  DETAILS_HOSTNAME: https://opsta.konmek.cloud/details
  REVIEWS_HOSTNAME: https://opsta.konmek.cloud/reviews
  FLOOD_FACTOR: 0
  COMMIT_SHA: CHANGEME